apply plugin: 'com.android.library'

dependencies {
    implementation 'androidx.health.connect:connect-client:1.1.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2'
    implementation 'androidx.work:work-runtime-ktx:2.11.2'
    implementation('com.jjoe64:graphview:4.2.2') {
        exclude group: 'com.android.support'
    }
}

android {
    namespace 'com.capstonedesign2026.platform'
    compileSdk 36

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    defaultConfig {
        minSdk 29
        targetSdk 36
    }

    sourceSets {
        main {
            manifest.srcFile 'src/main/AndroidManifest.xml'
            kotlin.srcDirs = ['src/main/kotlin']
            res.srcDirs = ['src/main/res']
        }
    }

    lint {
        abortOnError false
    }
}
