using System;
using System.Collections.Generic;

namespace CapstoneDesign.Runtime
{
    [Serializable]
    public sealed class MissionDefinition
    {
        public int mbctActivity;
        public string purpose;
        public MbctStep[] steps = Array.Empty<MbctStep>();
        public string id, sourceId, type, title, instructions;
        public int week, recommendedOrder, suggestedDurationSeconds, suggestedDurationMinSeconds, suggestedDurationMaxSeconds;
        public string suggestedDurationLabel, optionalReflection, audioReference, source, contentVersion, licenseReviewStatus;
        public string[] alternativeMissionIds = Array.Empty<string>();
        // Locally authored text alternative, never represented as a transcript or translation.
        public string textOnlyInstructions;
        public bool audioAvailable;
    }

    [Serializable]
    public sealed class GardenContentDefinition
    {
        public string id, sourceId, type, title, description, source, contentVersion;
        public string[] candidateAnimalIds;
    }

    [Serializable]
    public sealed class AnimalDefinition
    {
        public string id, sourceId, title, autonomousBehavior, tapReaction, source, contentVersion;
        // Association candidates only: the plan has not decided AND/OR conditions, rarity or probabilities.
        public string[] candidateEnvironmentIds;
    }

    [Serializable]
    public sealed class AudioReferenceDefinition
    {
        public string id, title, creator, source, licenseReviewStatus;
        public int durationSeconds;
        public bool bundled;
    }

    /// <summary>Bundled read-only catalog, faithfully transcribed from the fetched Notion draft.
    /// Definitions never own balances, completion, rewards, visit rolls or saved progress.</summary>
    public static class MindfulnessContent
    {
        public const string ContentVersion = "notion-2026-09-22";
        public const string AudioReviewPending = "NOT_BUNDLED_CONTENT_AND_LICENSE_REVIEW_PENDING";
        public const string CourseSource = "https://app.notion.com/p/3da7381534e2803db959e4833f848d69";
        public const string GardenSource = "https://app.notion.com/p/3de7381534e281dcb8eccd8c6b34fc17";
        public const string AnimalSource = "https://app.notion.com/p/3de7381534e281078616f0f412921943";
        public const string FreeMissionSource = "https://app.notion.com/p/3de7381534e281738240e43456c01ddd";

        public static readonly IReadOnlyList<string> WeekTitles = Array.AsReadOnly(new[] {
            "현재의 감각 알아차리기", "감정과 생각 알아차리기", "자신에게 친절하게 반응하기", "생활 속에서 이어가기"
        });

        public static readonly IReadOnlyList<MissionDefinition> Course = Array.AsReadOnly(new[] {
            new MissionDefinition { id = "course:P01", sourceId = "P01", type = "course", title = "잠깐 멈춰보기", instructions = "편한 자세로 음원 A를 듣고 호흡이 느껴지는 곳을 찾아본다.", week = 1, recommendedOrder = 1, suggestedDurationSeconds = 240, suggestedDurationMinSeconds = 240, suggestedDurationMaxSeconds = 240, suggestedDurationLabel = "A · 약 4분", optionalReflection = "코·가슴·배 중 어디에서 느꼈나요? 잘 모르겠어요도 가능", audioReference = "A", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = AudioReviewPending, textOnlyInstructions = "편한 자세에서 자연스러운 호흡이 느껴지는 곳을 살펴보세요. 호흡을 바꿀 필요는 없습니다." },
            new MissionDefinition { id = "course:P02", sourceId = "P02", type = "course", title = "주변 소리 만나기", instructions = "눈을 뜨거나 감은 편한 상태에서 C를 듣고 기억나는 소리 하나를 고른다.", week = 1, recommendedOrder = 2, suggestedDurationSeconds = 240, suggestedDurationMinSeconds = 240, suggestedDurationMaxSeconds = 240, suggestedDurationLabel = "C · 약 4분", optionalReflection = "어떤 소리가 들렸나요?", audioReference = "C", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = AudioReviewPending, textOnlyInstructions = "편한 자세에서 주변에 들리는 소리 하나에 잠시 주의를 두세요." },
            new MissionDefinition { id = "course:P03", sourceId = "P03", type = "course", title = "몸에 안부 묻기", instructions = "B를 듣고 몸에서 느껴진 감각 하나를 확인한다.", week = 1, recommendedOrder = 3, suggestedDurationSeconds = 300, suggestedDurationMinSeconds = 300, suggestedDurationMaxSeconds = 300, suggestedDurationLabel = "B · 약 5분", optionalReflection = "따뜻함·차가움·압박감·특별한 느낌 없음 중 무엇에 가까운가요?", audioReference = "B", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = AudioReviewPending, textOnlyInstructions = "편한 자세에서 몸이 의자나 바닥에 닿는 감각을 살펴보세요." },
            new MissionDefinition { id = "course:P04", sourceId = "P04", type = "course", title = "한 모금 천천히", instructions = "편한 온도의 물이나 음료를 준비하고 컵의 감촉·온도·맛을 느끼며 한 모금 마신다.", week = 1, recommendedOrder = 4, suggestedDurationSeconds = 180, suggestedDurationMinSeconds = 180, suggestedDurationMaxSeconds = 180, suggestedDurationLabel = "생활 · 약 3분", optionalReflection = "평소 지나쳤던 감각이 있었나요?", audioReference = "", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = "APP_AUTHORED_DRAFT_REVIEW_PENDING", textOnlyInstructions = "편한 온도의 물이나 음료를 준비하고 컵의 감촉·온도·맛을 느끼며 한 모금 마신다." },
            new MissionDefinition { id = "course:P05", sourceId = "P05", type = "course", title = "다시 돌아오기", instructions = "A 실습 중 다른 생각이 들면 알아차리고 호흡으로 돌아온다. 횟수는 세지 않는다.", week = 1, recommendedOrder = 5, suggestedDurationSeconds = 240, suggestedDurationMinSeconds = 240, suggestedDurationMaxSeconds = 240, suggestedDurationLabel = "A · 약 4분", optionalReflection = "다른 생각을 알아차린 순간이 있었나요?", audioReference = "A", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = AudioReviewPending, textOnlyInstructions = "생각이 떠오른 것을 알아차리면 편한 호흡의 감각으로 돌아와 보세요. 횟수는 세지 않아도 됩니다." },
            new MissionDefinition { id = "course:P06", sourceId = "P06", type = "course", title = "익숙한 행동 새롭게", instructions = "손 씻기나 설거지 중 물의 온도·움직임·소리를 관찰한다.", week = 1, recommendedOrder = 6, suggestedDurationSeconds = 180, suggestedDurationMinSeconds = 180, suggestedDurationMaxSeconds = 180, suggestedDurationLabel = "생활 · 약 3분", optionalReflection = "오늘 새롭게 느낀 감각은 무엇인가요?", audioReference = "", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = "APP_AUTHORED_DRAFT_REVIEW_PENDING", textOnlyInstructions = "손 씻기나 설거지 중 물의 온도·움직임·소리를 관찰한다." },
            new MissionDefinition { id = "course:P07", sourceId = "P07", type = "course", title = "나에게 편한 실습 찾기", instructions = "A·B·C 중 가장 부담이 적었던 것을 한 번 더 수행한다.", week = 1, recommendedOrder = 7, suggestedDurationSeconds = 300, suggestedDurationMinSeconds = 240, suggestedDurationMaxSeconds = 300, suggestedDurationLabel = "선택 · 약 4~5분", optionalReflection = "다음에도 해보고 싶은 활동은 무엇인가요?", audioReference = "A,B,C", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = AudioReviewPending, textOnlyInstructions = "호흡, 몸의 접촉 감각, 주변 소리 중 편한 대상 하나를 골라 잠시 관찰해 보세요." },
            new MissionDefinition { id = "course:P08", sourceId = "P08", type = "course", title = "마음에 이름 붙이기", instructions = "현재 기분을 한 단어로 선택한 뒤 A를 수행한다.", week = 2, recommendedOrder = 8, suggestedDurationSeconds = 300, suggestedDurationMinSeconds = 300, suggestedDurationMaxSeconds = 300, suggestedDurationLabel = "A+선택 · 약 5분", optionalReflection = "지금 마음을 표현할 단어가 있나요?", audioReference = "A", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = AudioReviewPending, textOnlyInstructions = "원한다면 지금 기분을 한 단어로 떠올린 뒤 자연스러운 호흡을 관찰해 보세요. 기분 확인은 건너뛰어도 됩니다." },
            new MissionDefinition { id = "course:P09", sourceId = "P09", type = "course", title = "감정과 몸 살펴보기", instructions = "B 실습 후 감정과 함께 느껴지는 몸의 감각이 있는지 확인한다.", week = 2, recommendedOrder = 9, suggestedDurationSeconds = 300, suggestedDurationMinSeconds = 300, suggestedDurationMaxSeconds = 300, suggestedDurationLabel = "B · 약 5분", optionalReflection = "몸에서 눈에 띈 느낌이 있었나요?", audioReference = "B", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = AudioReviewPending, textOnlyInstructions = "몸이 의자나 바닥에 닿는 감각을 살펴보세요. 감정과 함께 느껴지는 감각이 있는지도 편하게 알아차려 보세요." },
            new MissionDefinition { id = "course:P10", sourceId = "P10", type = "course", title = "잠시 숨 고르기", instructions = "일상 활동 사이에 멈춰 D를 따라 실습한다.", week = 2, recommendedOrder = 10, suggestedDurationSeconds = 240, suggestedDurationMinSeconds = 240, suggestedDurationMaxSeconds = 240, suggestedDurationLabel = "D · 약 4분", optionalReflection = "멈추기 전에는 무엇을 하고 있었나요?", audioReference = "D", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = AudioReviewPending, textOnlyInstructions = "하던 일을 잠시 멈추고 지금의 몸과 마음을 살펴보세요. 자연스러운 호흡을 느낀 뒤 주변으로 주의를 넓혀 보세요." },
            new MissionDefinition { id = "course:P11", sourceId = "P11", type = "course", title = "생각이 왔음을 알아차리기", instructions = "A 실습 중 생각이 떠오르면 ‘생각이구나’라고 알아차리고 돌아온다. 생각의 내용은 적지 않아도 된다.", week = 2, recommendedOrder = 11, suggestedDurationSeconds = 240, suggestedDurationMinSeconds = 240, suggestedDurationMaxSeconds = 240, suggestedDurationLabel = "A · 약 4분", optionalReflection = "생각이 왔다가 달라지는 것을 알아차렸나요?", audioReference = "A", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = AudioReviewPending, textOnlyInstructions = "호흡을 느끼다가 생각이 떠오르면 '생각이구나' 하고 알아차려 보세요. 생각의 내용은 적지 않아도 됩니다." },
            new MissionDefinition { id = "course:P12", sourceId = "P12", type = "course", title = "작은 편안함 찾기", instructions = "햇볕·음료·음악 등 괜찮게 느껴지는 경험 하나에 주의를 둔다. 찾지 못해도 괜찮다.", week = 2, recommendedOrder = 12, suggestedDurationSeconds = 180, suggestedDurationMinSeconds = 180, suggestedDurationMaxSeconds = 180, suggestedDurationLabel = "생활 · 약 3분", optionalReflection = "괜찮게 느껴진 순간이 있었나요?", audioReference = "", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = "APP_AUTHORED_DRAFT_REVIEW_PENDING", textOnlyInstructions = "햇볕·음료·음악 등 괜찮게 느껴지는 경험 하나에 주의를 둔다. 찾지 못해도 괜찮다." },
            new MissionDefinition { id = "course:P13", sourceId = "P13", type = "course", title = "마음이 바뀌어도 괜찮기", instructions = "D 실습 전후 기분을 선택한다. 좋아짐·같음·불편해짐을 동등하게 기록한다.", week = 2, recommendedOrder = 13, suggestedDurationSeconds = 300, suggestedDurationMinSeconds = 300, suggestedDurationMaxSeconds = 300, suggestedDurationLabel = "D+선택 · 약 5분", optionalReflection = "전후 느낌이 달랐나요, 비슷했나요?", audioReference = "D", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = AudioReviewPending, textOnlyInstructions = "잠시 멈추고 자연스러운 호흡이나 주변 소리를 관찰해 보세요. 원한다면 전후 느낌을 남겨보세요. 어떤 변화도 평가하지 않습니다." },
            new MissionDefinition { id = "course:P14", sourceId = "P14", type = "course", title = "내게 맞는 방식 확인하기", instructions = "편했던 실습을 반복하고 앞으로 더 자주 또는 덜 자주 하고 싶은 활동을 선택한다.", week = 2, recommendedOrder = 14, suggestedDurationSeconds = 300, suggestedDurationMinSeconds = 240, suggestedDurationMaxSeconds = 300, suggestedDurationLabel = "A·B·C·D · 약 4~5분", optionalReflection = "무엇을 더 자주, 덜 자주 하고 싶나요?", audioReference = "A,B,C,D", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = AudioReviewPending, textOnlyInstructions = "호흡, 몸의 접촉 감각, 주변 소리 중 편했던 대상을 잠시 관찰해 보세요. 더 자주 또는 덜 자주 하고 싶은 것을 떠올려 보세요." },
            new MissionDefinition { id = "course:P15", sourceId = "P15", type = "course", title = "나에게 한마디", instructions = "A 실습 후 자신에게 건넬 문장을 선택하거나 쓴다. 예: ‘잠깐 쉬어도 괜찮아.’", week = 3, recommendedOrder = 15, suggestedDurationSeconds = 300, suggestedDurationMinSeconds = 300, suggestedDurationMaxSeconds = 300, suggestedDurationLabel = "A+한 문장 · 약 5분", optionalReflection = "지금 듣고 싶은 말은 무엇인가요?", audioReference = "A", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = AudioReviewPending, textOnlyInstructions = "자연스러운 호흡을 잠시 관찰한 뒤 자신에게 건넬 말을 떠올려 보세요. 기록은 건너뛰어도 됩니다." },
            new MissionDefinition { id = "course:P16", sourceId = "P16", type = "course", title = "몸이 편한 자세 찾기", instructions = "의자·등받이·발 위치를 조절한 뒤 B를 수행한다.", week = 3, recommendedOrder = 16, suggestedDurationSeconds = 300, suggestedDurationMinSeconds = 300, suggestedDurationMaxSeconds = 300, suggestedDurationLabel = "B · 약 5분", optionalReflection = "어떤 조절이 더 편했나요?", audioReference = "B", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = AudioReviewPending, textOnlyInstructions = "의자, 등받이, 발 위치를 편하게 조절한 뒤 몸이 닿는 감각을 살펴보세요." },
            new MissionDefinition { id = "course:P17", sourceId = "P17", type = "course", title = "나를 돕는 작은 행동", instructions = "D 실습 후 물 마시기·잠깐 쉬기·창밖 보기 중 원하는 행동 하나를 한다.", week = 3, recommendedOrder = 17, suggestedDurationSeconds = 300, suggestedDurationMinSeconds = 300, suggestedDurationMaxSeconds = 300, suggestedDurationLabel = "D+생활 · 약 5분", optionalReflection = "지금 필요한 것은 무엇이었나요?", audioReference = "D", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = AudioReviewPending, textOnlyInstructions = "잠시 멈춰 몸과 마음을 살펴본 뒤 물 마시기, 쉬기, 창밖 보기 중 원하는 행동을 해보세요." },
            new MissionDefinition { id = "course:P18", sourceId = "P18", type = "course", title = "실습을 바꿔도 괜찮기", instructions = "호흡과 소리 중 오늘 편한 대상을 골라 실습한다. 불편하면 중간에 바꿀 수 있다.", week = 3, recommendedOrder = 18, suggestedDurationSeconds = 240, suggestedDurationMinSeconds = 240, suggestedDurationMaxSeconds = 240, suggestedDurationLabel = "A 또는 C · 약 4분", optionalReflection = "무엇을 기준으로 골랐나요?", audioReference = "A,C", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = AudioReviewPending, textOnlyInstructions = "자연스러운 호흡과 주변 소리 중 오늘 편한 대상을 관찰해 보세요. 불편하면 대상을 바꾸거나 중단해도 됩니다." },
            new MissionDefinition { id = "course:P19", sourceId = "P19", type = "course", title = "산 명상 경험하기", instructions = "E를 따라 해본다. 길게 느껴지면 C로 대체한다.", week = 3, recommendedOrder = 19, suggestedDurationSeconds = 540, suggestedDurationMinSeconds = 240, suggestedDurationMaxSeconds = 540, suggestedDurationLabel = "E 약 9분 / C 약 4분", optionalReflection = "이 방식은 나에게 편했나요?", audioReference = "E,C", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = AudioReviewPending, textOnlyInstructions = "산 명상 음원은 아직 준비되지 않았습니다. 대신 편한 자세에서 주변 소리 하나에 잠시 주의를 두어 보세요." },
            new MissionDefinition { id = "course:P20", sourceId = "P20", type = "course", title = "오늘의 시도 인정하기", instructions = "짧은 실습 후 오늘 자신을 위해 한 행동 하나를 적거나 선택한다.", week = 3, recommendedOrder = 20, suggestedDurationSeconds = 300, suggestedDurationMinSeconds = 300, suggestedDurationMaxSeconds = 300, suggestedDurationLabel = "A 또는 C+기록 · 약 5분", optionalReflection = "오늘 나를 위해 한 작은 행동은 무엇인가요?", audioReference = "A,C", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = AudioReviewPending, textOnlyInstructions = "자연스러운 호흡이나 주변 소리를 잠시 관찰한 뒤 오늘 자신을 위해 한 행동을 떠올려 보세요. 기록은 선택입니다." },
            new MissionDefinition { id = "course:P21", sourceId = "P21", type = "course", title = "나만의 쉬는 방법 정하기", instructions = "편했던 활동을 수행하고 ‘내 쉬는 방법’으로 기록한다.", week = 3, recommendedOrder = 21, suggestedDurationSeconds = 540, suggestedDurationMinSeconds = 240, suggestedDurationMaxSeconds = 540, suggestedDurationLabel = "선택 · 약 4~9분", optionalReflection = "힘든 날에도 부담 없이 할 수 있는 것은 무엇인가요?", audioReference = "", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = AudioReviewPending, textOnlyInstructions = "편했던 짧은 활동을 한 번 해보세요. 원한다면 '내 쉬는 방법'으로 기록해 보세요." },
            new MissionDefinition { id = "course:P22", sourceId = "P22", type = "course", title = "이동하는 감각 느끼기", instructions = "안전한 장소에서 천천히 이동하며 발이나 몸이 바닥·의자에 닿는 감각을 관찰한다. 이동이 어려우면 앉아서 접촉 감각을 느낀다.", week = 4, recommendedOrder = 22, suggestedDurationSeconds = 180, suggestedDurationMinSeconds = 180, suggestedDurationMaxSeconds = 180, suggestedDurationLabel = "생활 · 약 3분", optionalReflection = "어떤 접촉 감각이 느껴졌나요?", audioReference = "", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = "APP_AUTHORED_DRAFT_REVIEW_PENDING", textOnlyInstructions = "안전한 장소에서 천천히 이동하며 발이나 몸이 바닥·의자에 닿는 감각을 관찰한다. 이동이 어려우면 앉아서 접촉 감각을 느낀다." },
            new MissionDefinition { id = "course:P23", sourceId = "P23", type = "course", title = "한입에 주의 기울이기", instructions = "식사 중 한입의 향·온도·질감을 관찰한다. 식사량이나 속도를 평가하지 않는다.", week = 4, recommendedOrder = 23, suggestedDurationSeconds = 180, suggestedDurationMinSeconds = 180, suggestedDurationMaxSeconds = 180, suggestedDurationLabel = "생활 · 약 3분", optionalReflection = "가장 또렷했던 감각은 무엇인가요?", audioReference = "", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = "APP_AUTHORED_DRAFT_REVIEW_PENDING", textOnlyInstructions = "식사 중 한입의 향·온도·질감을 관찰한다. 식사량이나 속도를 평가하지 않는다." },
            new MissionDefinition { id = "course:P24", sourceId = "P24", type = "course", title = "들리는 말에 집중하기", instructions = "상대가 편하게 나누는 짧은 이야기를 듣는다. 대화 기회가 없으면 짧은 이야기 음성을 듣는다.", week = 4, recommendedOrder = 24, suggestedDurationSeconds = 180, suggestedDurationMinSeconds = 180, suggestedDurationMaxSeconds = 180, suggestedDurationLabel = "생활 · 약 3분", optionalReflection = "내용 중 무엇이 기억나나요?", audioReference = "", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = "APP_AUTHORED_DRAFT_REVIEW_PENDING", textOnlyInstructions = "상대가 편하게 나누는 짧은 이야기를 듣는다. 대화 기회가 없으면 짧은 이야기 음성을 듣는다." },
            new MissionDefinition { id = "course:P25", sourceId = "P25", type = "course", title = "말하기 전에 잠깐 멈추기", instructions = "메시지를 보내거나 말하기 전에 잠시 멈추고 전달하고 싶은 내용을 확인한다.", week = 4, recommendedOrder = 25, suggestedDurationSeconds = 120, suggestedDurationMinSeconds = 120, suggestedDurationMaxSeconds = 120, suggestedDurationLabel = "생활 · 약 2분", optionalReflection = "내가 전하고 싶은 핵심은 무엇이었나요?", audioReference = "", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = "APP_AUTHORED_DRAFT_REVIEW_PENDING", textOnlyInstructions = "메시지를 보내거나 말하기 전에 잠시 멈추고 전달하고 싶은 내용을 확인한다." },
            new MissionDefinition { id = "course:P26", sourceId = "P26", type = "course", title = "사소한 도움 알아차리기", instructions = "오늘 도움이 된 사람·물건·환경 중 하나를 떠올린다. 찾기 어렵다면 C를 수행한다.", week = 4, recommendedOrder = 26, suggestedDurationSeconds = 240, suggestedDurationMinSeconds = 180, suggestedDurationMaxSeconds = 240, suggestedDurationLabel = "생활 또는 C · 약 3~4분", optionalReflection = "오늘 무엇이 작은 도움이 되었나요?", audioReference = "C", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = AudioReviewPending, textOnlyInstructions = "오늘 도움이 된 사람, 물건, 환경 중 하나를 떠올려 보세요. 어렵다면 주변 소리 하나에 잠시 주의를 두어 보세요." },
            new MissionDefinition { id = "course:P27", sourceId = "P27", type = "course", title = "생활에 실습 연결하기", instructions = "‘점심 후’, ‘샤워 후’ 등 기존 행동 하나를 정하고 그 뒤 A·B·C 중 하나를 수행한다.", week = 4, recommendedOrder = 27, suggestedDurationSeconds = 300, suggestedDurationMinSeconds = 240, suggestedDurationMaxSeconds = 300, suggestedDurationLabel = "선택 · 약 4~5분", optionalReflection = "언제 하면 덜 부담스러웠나요?", audioReference = "A,B,C", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = AudioReviewPending, textOnlyInstructions = "기존 행동 하나를 정하고 그 뒤 자연스러운 호흡, 몸의 접촉 감각, 주변 소리 중 하나를 관찰해 보세요." },
            new MissionDefinition { id = "course:P28", sourceId = "P28", type = "course", title = "다음 주의 나 돌보기", instructions = "좋아하는 실습을 수행하고 다음 주에 다시 할 활동·시간대를 한 가지씩 정한다.", week = 4, recommendedOrder = 28, suggestedDurationSeconds = 600, suggestedDurationMinSeconds = 300, suggestedDurationMaxSeconds = 600, suggestedDurationLabel = "선택+계획 · 약 5~10분", optionalReflection = "앞으로 어떤 방식으로 이어가고 싶나요?", audioReference = "", source = CourseSource, contentVersion = ContentVersion, licenseReviewStatus = AudioReviewPending, textOnlyInstructions = "편한 실습을 해본 뒤 다음 주 다시 해보고 싶은 활동과 시간대를 떠올려 보세요. 기록은 선택입니다." },
        });

        public static readonly IReadOnlyList<MissionDefinition> FreeMissions = Array.AsReadOnly(new[] {
            new MissionDefinition { id = "free-mission:M01", sourceId = "M01", type = "free-mission", title = "주변 밝히기", instructions = "커튼을 열거나 조명 켜기", textOnlyInstructions = "커튼을 열거나 조명 켜기", source = FreeMissionSource, contentVersion = "notion-2026-09-18", suggestedDurationLabel = "미정", optionalReflection = "", audioReference = "", licenseReviewStatus = "APP_AUTHORED_DRAFT_REVIEW_PENDING" },
            new MissionDefinition { id = "free-mission:M02", sourceId = "M02", type = "free-mission", title = "창밖 바라보기", instructions = "창밖에서 눈에 들어온 풍경 하나 살펴보기", textOnlyInstructions = "창밖에서 눈에 들어온 풍경 하나 살펴보기", source = FreeMissionSource, contentVersion = "notion-2026-09-18", suggestedDurationLabel = "미정", optionalReflection = "", audioReference = "", licenseReviewStatus = "APP_AUTHORED_DRAFT_REVIEW_PENDING" },
            new MissionDefinition { id = "free-mission:M03", sourceId = "M03", type = "free-mission", title = "물 마시기", instructions = "편한 때 물 마시기", textOnlyInstructions = "편한 때 물 마시기", source = FreeMissionSource, contentVersion = "notion-2026-09-18", suggestedDurationLabel = "미정", optionalReflection = "", audioReference = "", licenseReviewStatus = "APP_AUTHORED_DRAFT_REVIEW_PENDING" },
            new MissionDefinition { id = "free-mission:M04", sourceId = "M04", type = "free-mission", title = "세수하기", instructions = "편한 방식으로 얼굴 씻기", textOnlyInstructions = "편한 방식으로 얼굴 씻기", source = FreeMissionSource, contentVersion = "notion-2026-09-18", suggestedDurationLabel = "미정", optionalReflection = "", audioReference = "", licenseReviewStatus = "APP_AUTHORED_DRAFT_REVIEW_PENDING" },
            new MissionDefinition { id = "free-mission:M05", sourceId = "M05", type = "free-mission", title = "가볍게 몸 펴기", instructions = "편한 자세에서 가능한 동작 하나 해보기", textOnlyInstructions = "편한 자세에서 가능한 동작 하나 해보기", source = FreeMissionSource, contentVersion = "notion-2026-09-18", suggestedDurationLabel = "미정", optionalReflection = "", audioReference = "", licenseReviewStatus = "APP_AUTHORED_DRAFT_REVIEW_PENDING" },
            new MissionDefinition { id = "free-mission:M06", sourceId = "M06", type = "free-mission", title = "물건 하나 정리", instructions = "눈앞의 물건 하나 제자리에 두기", textOnlyInstructions = "눈앞의 물건 하나 제자리에 두기", source = FreeMissionSource, contentVersion = "notion-2026-09-18", suggestedDurationLabel = "미정", optionalReflection = "", audioReference = "", licenseReviewStatus = "APP_AUTHORED_DRAFT_REVIEW_PENDING" },
            new MissionDefinition { id = "free-mission:M07", sourceId = "M07", type = "free-mission", title = "기분 살피기", instructions = "지금 기분을 한 단어나 짧은 문장으로 적기", textOnlyInstructions = "지금 기분을 한 단어나 짧은 문장으로 적기", source = FreeMissionSource, contentVersion = "notion-2026-09-18", suggestedDurationLabel = "미정", optionalReflection = "", audioReference = "", licenseReviewStatus = "APP_AUTHORED_DRAFT_REVIEW_PENDING" },
            new MissionDefinition { id = "free-mission:M08", sourceId = "M08", type = "free-mission", title = "음악 듣기", instructions = "원하는 음악을 편한 만큼 듣기", textOnlyInstructions = "원하는 음악을 편한 만큼 듣기", source = FreeMissionSource, contentVersion = "notion-2026-09-18", suggestedDurationLabel = "미정", optionalReflection = "", audioReference = "", licenseReviewStatus = "APP_AUTHORED_DRAFT_REVIEW_PENDING" },
            new MissionDefinition { id = "free-mission:M09", sourceId = "M09", type = "free-mission", title = "잠깐 쉬기", instructions = "하던 일을 멈추고 편하게 쉬기", textOnlyInstructions = "하던 일을 멈추고 편하게 쉬기", source = FreeMissionSource, contentVersion = "notion-2026-09-18", suggestedDurationLabel = "미정", optionalReflection = "", audioReference = "", licenseReviewStatus = "APP_AUTHORED_DRAFT_REVIEW_PENDING" },
            new MissionDefinition { id = "free-mission:M10", sourceId = "M10", type = "free-mission", title = "작은 계획 세우기", instructions = "오늘 하고 싶은 일 하나 적기", textOnlyInstructions = "오늘 하고 싶은 일 하나 적기", source = FreeMissionSource, contentVersion = "notion-2026-09-18", suggestedDurationLabel = "미정", optionalReflection = "", audioReference = "", licenseReviewStatus = "APP_AUTHORED_DRAFT_REVIEW_PENDING" },
            new MissionDefinition { id = "free-mission:M11", sourceId = "M11", type = "free-mission", title = "자유롭게 낙서", instructions = "떠오르는 선이나 모양 그리기", textOnlyInstructions = "떠오르는 선이나 모양 그리기", source = FreeMissionSource, contentVersion = "notion-2026-09-18", suggestedDurationLabel = "미정", optionalReflection = "", audioReference = "", licenseReviewStatus = "APP_AUTHORED_DRAFT_REVIEW_PENDING" },
            new MissionDefinition { id = "free-mission:M12", sourceId = "M12", type = "free-mission", title = "주변 식물 살피기", instructions = "가까운 식물의 잎·색·모양 살펴보기", textOnlyInstructions = "가까운 식물의 잎·색·모양 살펴보기", source = FreeMissionSource, contentVersion = "notion-2026-09-18", suggestedDurationLabel = "미정", optionalReflection = "", audioReference = "", licenseReviewStatus = "APP_AUTHORED_DRAFT_REVIEW_PENDING" },
            new MissionDefinition { id = "free-mission:M13", sourceId = "M13", type = "free-mission", title = "괜찮았던 순간", instructions = "오늘 괜찮았던 순간 하나 떠올리기", textOnlyInstructions = "오늘 괜찮았던 순간 하나 떠올리기", source = FreeMissionSource, contentVersion = "notion-2026-09-18", suggestedDurationLabel = "미정", optionalReflection = "", audioReference = "", licenseReviewStatus = "APP_AUTHORED_DRAFT_REVIEW_PENDING" },
            new MissionDefinition { id = "free-mission:M14", sourceId = "M14", type = "free-mission", title = "짧은 글 읽기", instructions = "관심 있는 글을 편한 만큼 읽기", textOnlyInstructions = "관심 있는 글을 편한 만큼 읽기", source = FreeMissionSource, contentVersion = "notion-2026-09-18", suggestedDurationLabel = "미정", optionalReflection = "", audioReference = "", licenseReviewStatus = "APP_AUTHORED_DRAFT_REVIEW_PENDING" },
            new MissionDefinition { id = "free-mission:M15", sourceId = "M15", type = "free-mission", title = "일정 걸음 걷기", instructions = "안전한 곳에서 편한 속도로 걸어 보세요. 일반 데모 목표는 300걸음이며, 건강 기록 동기화가 늦어도 직접 완료할 수 있어요.", textOnlyInstructions = "안전한 곳에서 편한 속도로 걸어 보세요. 일반 데모 목표는 300걸음이며, 건강 기록 동기화가 늦어도 직접 완료할 수 있어요.", source = FreeMissionSource, contentVersion = "notion-2026-09-18", suggestedDurationLabel = "미정", optionalReflection = "", audioReference = "", licenseReviewStatus = "APP_AUTHORED_DRAFT_REVIEW_PENDING" },
            new MissionDefinition { id = "free-mission:M16", sourceId = "M16", type = "free-mission", title = "공원 방문", instructions = "가까운 공원에 방문하기", textOnlyInstructions = "가까운 공원에 방문하기", source = FreeMissionSource, contentVersion = "notion-2026-09-18", suggestedDurationLabel = "미정", optionalReflection = "", audioReference = "", licenseReviewStatus = "APP_AUTHORED_DRAFT_REVIEW_PENDING" },
            new MissionDefinition { id = "free-mission:M17", sourceId = "M17", type = "free-mission", title = "안내 따라 호흡", instructions = "안내에 따라 편한 속도로 호흡하기", textOnlyInstructions = "안내에 따라 편한 속도로 호흡하기", source = FreeMissionSource, contentVersion = "notion-2026-09-18", suggestedDurationLabel = "미정", optionalReflection = "", audioReference = "", licenseReviewStatus = "APP_AUTHORED_DRAFT_REVIEW_PENDING" },
        });

        public static readonly IReadOnlyList<GardenContentDefinition> Plants = Array.AsReadOnly(new[] {
            new GardenContentDefinition { id = "plant:P01", sourceId = "P01", type = "plant", title = "해바라기", description = "새싹 → 큰 줄기·꽃", candidateAnimalIds = new[] { "animal:A02", "animal:A05" }, source = GardenSource, contentVersion = "notion-2026-09-18" },
            new GardenContentDefinition { id = "plant:P02", sourceId = "P02", type = "plant", title = "라벤더", description = "모종 → 보라색 꽃무리", candidateAnimalIds = new[] { "animal:A01", "animal:A04" }, source = GardenSource, contentVersion = "notion-2026-09-18" },
            new GardenContentDefinition { id = "plant:P03", sourceId = "P03", type = "plant", title = "데이지", description = "잎 → 흰 꽃무리", candidateAnimalIds = new[] { "animal:A07", "animal:A12" }, source = GardenSource, contentVersion = "notion-2026-09-18" },
            new GardenContentDefinition { id = "plant:P04", sourceId = "P04", type = "plant", title = "클로버", description = "작은 잎 → 낮은 잎·꽃무리", candidateAnimalIds = new[] { "animal:A07", "animal:A10" }, source = GardenSource, contentVersion = "notion-2026-09-18" },
            new GardenContentDefinition { id = "plant:P05", sourceId = "P05", type = "plant", title = "수국", description = "어린 관목 → 둥근 꽃송이", candidateAnimalIds = new[] { "animal:A04", "animal:A09" }, source = GardenSource, contentVersion = "notion-2026-09-18" },
            new GardenContentDefinition { id = "plant:P06", sourceId = "P06", type = "plant", title = "단풍나무", description = "묘목 → 넓은 수관", candidateAnimalIds = new[] { "animal:A05", "animal:A06", "animal:A08" }, source = GardenSource, contentVersion = "notion-2026-09-18" },
        });

        public static readonly IReadOnlyList<GardenContentDefinition> Environments = Array.AsReadOnly(new[] {
            new GardenContentDefinition { id = "environment:E01", sourceId = "E01", type = "environment", title = "꽃밭", description = "낮은 경계와 꽃 식재 공간", candidateAnimalIds = new[] { "animal:A07", "animal:A12" }, source = GardenSource, contentVersion = "notion-2026-09-18" },
            new GardenContentDefinition { id = "environment:E02", sourceId = "E02", type = "environment", title = "쉼터", description = "목재 지붕과 그늘 공간", candidateAnimalIds = new[] { "animal:A01", "animal:A03", "animal:A07", "animal:A09", "animal:A10" }, source = GardenSource, contentVersion = "notion-2026-09-18" },
            new GardenContentDefinition { id = "environment:E03", sourceId = "E03", type = "environment", title = "연못", description = "얕은 수면과 풀 가장자리", candidateAnimalIds = new[] { "animal:A10", "animal:A11", "animal:A12" }, source = GardenSource, contentVersion = "notion-2026-09-18" },
            new GardenContentDefinition { id = "environment:E04", sourceId = "E04", type = "environment", title = "통나무", description = "눕힌 나무와 주변 풀", candidateAnimalIds = new[] { "animal:A02", "animal:A04", "animal:A06", "animal:A08", "animal:A09" }, source = GardenSource, contentVersion = "notion-2026-09-18" },
            new GardenContentDefinition { id = "environment:E05", sourceId = "E05", type = "environment", title = "돌길", description = "식물 사이를 잇는 낮은 돌", candidateAnimalIds = new[] { "animal:A01", "animal:A02", "animal:A03" }, source = GardenSource, contentVersion = "notion-2026-09-18" },
            new GardenContentDefinition { id = "environment:E06", sourceId = "E06", type = "environment", title = "새 물그릇", description = "낮은 받침과 작은 물그릇", candidateAnimalIds = new[] { "animal:A05" }, source = GardenSource, contentVersion = "notion-2026-09-18" },
        });

        public static readonly IReadOnlyList<AnimalDefinition> Animals = Array.AsReadOnly(new[] {
            new AnimalDefinition { id = "animal:A01", sourceId = "A01", title = "고양이", candidateEnvironmentIds = new[] { "plant:P02", "environment:E02", "environment:E05" }, autonomousBehavior = "그늘에서 낮잠·기지개", tapReaction = "눈 천천히 깜빡이기", source = AnimalSource, contentVersion = "notion-2026-09-18" },
            new AnimalDefinition { id = "animal:A02", sourceId = "A02", title = "아르마딜로", candidateEnvironmentIds = new[] { "plant:P01", "environment:E04", "environment:E05" }, autonomousBehavior = "코로 주변 살피기·느린 산책", tapReaction = "몸 웅크리기", source = AnimalSource, contentVersion = "notion-2026-09-18" },
            new AnimalDefinition { id = "animal:A03", sourceId = "A03", title = "사막여우", candidateEnvironmentIds = new[] { "environment:E02", "environment:E05" }, autonomousBehavior = "큰 귀 움직이기·가볍게 뛰기", tapReaction = "고개 갸웃하기", source = AnimalSource, contentVersion = "notion-2026-09-18" },
            new AnimalDefinition { id = "animal:A04", sourceId = "A04", title = "친칠라", candidateEnvironmentIds = new[] { "plant:P02", "plant:P05", "environment:E04" }, autonomousBehavior = "작게 뛰기·앞발로 얼굴 닦기", tapReaction = "귀 쫑긋하기", source = AnimalSource, contentVersion = "notion-2026-09-18" },
            new AnimalDefinition { id = "animal:A05", sourceId = "A05", title = "뱁새", candidateEnvironmentIds = new[] { "plant:P01", "plant:P06", "environment:E06" }, autonomousBehavior = "가지에 앉아 쉬기·짧게 뛰기", tapReaction = "깃털 부풀리기", source = AnimalSource, contentVersion = "notion-2026-09-18" },
            new AnimalDefinition { id = "animal:A06", sourceId = "A06", title = "레서판다", candidateEnvironmentIds = new[] { "plant:P06", "environment:E04" }, autonomousBehavior = "나무 오르기·가지에 기대 쉬기", tapReaction = "앞발 들기", source = AnimalSource, contentVersion = "notion-2026-09-18" },
            new AnimalDefinition { id = "animal:A07", sourceId = "A07", title = "토끼", candidateEnvironmentIds = new[] { "plant:P03", "plant:P04", "environment:E01", "environment:E02" }, autonomousBehavior = "풀 주변 뛰기·쉬기", tapReaction = "귀 쫑긋하기", source = AnimalSource, contentVersion = "notion-2026-09-18" },
            new AnimalDefinition { id = "animal:A08", sourceId = "A08", title = "다람쥐", candidateEnvironmentIds = new[] { "plant:P06", "environment:E04" }, autonomousBehavior = "나무 오르기·주변 이동", tapReaction = "꼬리 흔들기", source = AnimalSource, contentVersion = "notion-2026-09-18" },
            new AnimalDefinition { id = "animal:A09", sourceId = "A09", title = "고슴도치", candidateEnvironmentIds = new[] { "plant:P05", "environment:E02", "environment:E04" }, autonomousBehavior = "천천히 걷기·그늘에서 쉬기", tapReaction = "코 움찔하기", source = AnimalSource, contentVersion = "notion-2026-09-18" },
            new AnimalDefinition { id = "animal:A10", sourceId = "A10", title = "카피바라", candidateEnvironmentIds = new[] { "plant:P04", "environment:E02", "environment:E03" }, autonomousBehavior = "물가에 앉기·느긋한 산책", tapReaction = "눈 감고 고개 끄덕이기", source = AnimalSource, contentVersion = "notion-2026-09-18" },
            new AnimalDefinition { id = "animal:A11", sourceId = "A11", title = "수달", candidateEnvironmentIds = new[] { "environment:E03" }, autonomousBehavior = "헤엄치기·물가에서 뒹굴기", tapReaction = "앞발 비비기", source = AnimalSource, contentVersion = "notion-2026-09-18" },
            new AnimalDefinition { id = "animal:A12", sourceId = "A12", title = "오리", candidateEnvironmentIds = new[] { "plant:P03", "environment:E01", "environment:E03" }, autonomousBehavior = "헤엄치기·물가 걷기", tapReaction = "짧게 울기", source = AnimalSource, contentVersion = "notion-2026-09-18" },
        });

        public static readonly IReadOnlyList<AudioReferenceDefinition> AudioReferences = Array.AsReadOnly(new[] {
            new AudioReferenceDefinition { id = "A", title = "Three minute breathing", creator = "Peter Morgan", durationSeconds = 215, source = "https://www.freemindfulness.org/download", licenseReviewStatus = AudioReviewPending, bundled = false },
            new AudioReferenceDefinition { id = "B", title = "Four minute body scan", creator = "Melbourne Mindfulness Centre & Still Mind", durationSeconds = 241, source = "https://www.freemindfulness.org/download", licenseReviewStatus = AudioReviewPending, bundled = false },
            new AudioReferenceDefinition { id = "C", title = "Three minute mindfulness of sounds", creator = "Peter Morgan", durationSeconds = 182, source = "https://www.freemindfulness.org/download", licenseReviewStatus = AudioReviewPending, bundled = false },
            new AudioReferenceDefinition { id = "D", title = "Three Step Breathing Space", creator = "Peter Morgan", durationSeconds = 214, source = "https://www.freemindfulness.org/download", licenseReviewStatus = AudioReviewPending, bundled = false },
            new AudioReferenceDefinition { id = "E", title = "Mountain meditation", creator = "Peter Morgan", durationSeconds = 492, source = "https://www.freemindfulness.org/download", licenseReviewStatus = AudioReviewPending, bundled = false },
        });

        public static MissionDefinition FindMission(string typedId)
        {
            var mbct=MbctContent.Find(typedId); if(mbct!=null)return mbct;
            foreach (var item in Course) if (item.id == typedId) return item;
            foreach (var item in FreeMissions) if (item.id == typedId) return item;
            return null;
        }

        public static GardenContentDefinition FindGardenContent(string typedId)
        {
            foreach (var item in Plants) if (item.id == typedId) return item;
            foreach (var item in Environments) if (item.id == typedId) return item;
            return null;
        }

        public static AnimalDefinition FindAnimal(string typedId)
        {
            foreach (var item in Animals) if (item.id == typedId) return item;
            return null;
        }
    }
}
